# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    app.form.registration:
        class: App\Form\RegistrationFormType
    app.form.profile:
        class: App\Form\ProfileFormType    
        #if autowire set to true under _defaults we do not need to use tags
        #tags:
        #    - { name: form.type }       
    app.redirect_after_registration_subscriber:
        class: App\EventListener\RedirectAfterRegistrationSubscriber
        autowire: true
        tags:
            - { name: kernel.event_subscriber }                     

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: noreply@example.com
        sender_name: Sender name
    registration:
        form:
            type: App\Form\RegistrationFormType
        confirmation:
            enabled: true  
            template:   '@FOSUser/Registration/email.txt.twig'
            from_email:
                address:        itsmejasbirsingh@gmail.com
                sender_name:    Demo Registration  
    profile:
        form:
            type: App\Form\ProfileFormType 
    #resetting:
    #    email:
    #        from_email:
    #            address:        resetting@example.com
    #            sender_name:    Demo Resetting
    #        template:   email/password_resetting.email.twig